[package]
name = "enterprise"
version = "0.1.0"
authors = ["Juan Lulkin <juan@lulk.in>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
pest = "2.0"
pest_derive = "2.0"
cranelift = "0.63.0"
cranelift-module = "0.63.0"
cranelift-simplejit = "0.63.0"
